// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm6mhudVDDUKJwRIU0Y2mlty-co5jKmTw',
    appId: '1:769928571481:web:3c19726f689835c85c5f48',
    messagingSenderId: '769928571481',
    projectId: 'messaging-app-a52c1',
    authDomain: 'messaging-app-a52c1.firebaseapp.com',
    storageBucket: 'messaging-app-a52c1.appspot.com',
    measurementId: 'G-PKCNQXF2QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3UouPn5HDa1W2bMWcpylckmGKjJheF6U',
    appId: '1:769928571481:android:6fa13f41916b99425c5f48',
    messagingSenderId: '769928571481',
    projectId: 'messaging-app-a52c1',
    storageBucket: 'messaging-app-a52c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Uq4P1BLakarLDhNFDog5ouTtZSphqLs',
    appId: '1:769928571481:ios:91e0665a533b3e4e5c5f48',
    messagingSenderId: '769928571481',
    projectId: 'messaging-app-a52c1',
    storageBucket: 'messaging-app-a52c1.appspot.com',
    iosBundleId: 'com.example.flutterMessagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm6mhudVDDUKJwRIU0Y2mlty-co5jKmTw',
    appId: '1:769928571481:web:810752fd704d1d335c5f48',
    messagingSenderId: '769928571481',
    projectId: 'messaging-app-a52c1',
    authDomain: 'messaging-app-a52c1.firebaseapp.com',
    storageBucket: 'messaging-app-a52c1.appspot.com',
    measurementId: 'G-RCL765EGRN',
  );
}
